kind: Pod 
apiVersion: v1 
metadata:
  name: pod-from-cm
  namespace: demo
spec:
  containers:
    - name: env-var-configmap
      image: nginx
      envFrom:
        - configMapRef:
            name: example-configmap