apiVersion: v1
kind: Pod
metadata:
  name: secret-envars-test-pod
  namespace: demo
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: database-values
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: database-values
          key: password