# Overall version
version: @image.tag@
log:
 file: "D:/others/learn/OU_Training/Docker_and_Kuber/k8spatterns/random-generator/random.log"
# Always show details for the health checks
management:
 endpoint:
   health:
     show-details: always